spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    username: root
    password: xxx
    url: xxx
  redis:
    host: 127.0.0.1
    port: 6379
    password: xxx
    database: 0
    lettuce:
      pool:
        max-idle: 16
        max-active: 32
        min-idle: 8
  servlet:
    multipart:
      max-file-size: 1000MB

server:
  port: 9000
  reactive:
    session:
      timeout: 30m

mybatis:
  mapper-locations: classpath:**/mapper/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

logging:
  level:
    com.longking.concrete.mapper.*: trace

aliyun:
  oss:
    endpoint: xxx
    accessKeyId: xxx
    accessKeySecret: xxx
    bucketName: xxx
    maxSize: 5
    policy:
      expire: 300

pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  page-size-zero: false
